wip: seal block production
interlay/interbtc pull request #363
Opened 2021-11-05 17:05 UTC by savudani8

2021-11-09 15:43 UTC, gregdhill requested changes
@savudani8 can you cleanup the aura & grandpa dependencies? I think we can also remove some of these from the runtime crate too right?

2021-11-11 16:07 UTC, sander2 commented on standalone/src/service.rs
> +    let fut = transaction_pool.import_notification_stream().map(
Maybe I'm missing something, but it doesn't look like this map is doing anything - `map` is lazy and doesn't do any work unless you do something with the result

2021-11-30 12:42 UTC, gregdhill commented
See also: https://github.com/paritytech/substrate/issues/10239

2021-12-02 17:07 UTC, sander2 commented
I tested without docker again, but finalization still isn't working properly. I did some debugging and narrowed down the problem to the `author_extrinsicUpdate` message not being sent to the client with the finalized status, see https://github.com/paritytech/substrate/issues/10279

2022-05-10 10:22 UTC, closed without merging