feat: Collateralization thresholds upgrade
interlay/interbtc pull request #406
Opened 2021-12-08 16:45 UTC by savudani8

2021-12-08 16:54 UTC, gregdhill requested changes

2021-12-08 16:54 UTC, gregdhill commented on parachain/src/chain_spec.rs
> +                ), /* 330% */
Remove DOT values for testnet genesis.

2021-12-08 16:54 UTC, gregdhill commented on parachain/src/chain_spec.rs
> +                ), /* 330% */
Remove DOT values for Kintsugi genesis.

2021-12-08 16:54 UTC, gregdhill commented on parachain/src/chain_spec.rs
> +                ), /* 360% */
Remove KSM values for Interlay genesis.

2021-12-08 21:10 UTC, gregdhill submitted a review, later dismissed

2021-12-08 21:17 UTC, gregdhill approved these changes

2021-12-08 21:36 UTC, merged

2021-12-09 03:26 UTC, nud3l commented
@savudani8 please add a quick summary of the parameter changes in future PRs. So it's easier to check how the parameters should be changed. Thanks!

2021-12-09 03:30 UTC, nud3l commented on parachain/src/chain_spec.rs
> +                default_pair_kintsugi(CurrencyId::KSM),
@savudani8 @gregdhill why are the thresholds so heavily increased? We need to discuss these parameter changes before making changes. There is a risk/product trade-off here. Increasing the collateralization by 100% points is reducing the profitability of running a vault significantly.