feat: set release of arbitrary clients, remove "pending" field
interlay/interbtc pull request #706
Opened 2022-08-30 16:00 UTC by savudani8

- `CurrentClientRelease` is changed from a value store to a map of type `(Vec<u8>,  ClientRelease<T::Hash>)`
- No migration is necessary, since no release has been set on-chain
- The `PendingClientRelease` field and its associated migration have been removed. Using just the `CurrentClientRelease` would only delay a client auto-update by one block, which is negligible and worth the complexity reduction

2022-08-31 06:12 UTC, sander2 requested changes
> The PendingClientRelease field and its associated migration have been removed. Using just the CurrentClientRelease would only delay a client auto-update by one block plus the binary download time, which is negligible and worth the complexity reduction

I think you're missing the main goal of `PendingClientRelease`, which is to be able to batch `[authorize_upgrade, set_pending_client_release]` in a single governance proposal, and have the the CurrentRelease automatically change automatically at the exact time the upgrade is actually executed. So I think we should keep it for this reason. The side benefit that you are talking about, which is that the client can download the upgrade in advance, is imo indeed unnecessary complexity on the client side, and I am fine with not implementing that.

2022-09-01 07:37 UTC, gregdhill reviewed
Left a few nits and one question, but otherwise LGTM. I do also wonder if it is worth moving this logic to a separate crate however, I realize it doesn't do a whole lot but this pallet is already quite big, it's not distinctly related to the core functionality here and I can foresee related changes we may want to group together.

2022-09-01 07:37 UTC, gregdhill commented on crates/vault-registry/src/types.rs
> +            if let Some(release) = crate::PendingClientRelease::<T>::take(key) {
I'm wondering if we should `drain` the `PendingClientRelease` map instead?

2022-09-01 07:37 UTC, gregdhill commented on crates/vault-registry/src/lib.rs
> +            CurrentClientRelease::<T>::insert(client_name, release.clone());
Nit: `CurrentClientRelease` should be `CurrentClientReleases`

2022-09-01 07:37 UTC, gregdhill commented on crates/vault-registry/src/lib.rs
> +            PendingClientRelease::<T>::insert(client_name, release.clone());
Nit: `PendingClientRelease` should be `PendingClientReleases`

2022-09-05 13:02 UTC, gregdhill approved these changes

2022-09-05 13:02 UTC, merged